# Generated by Django 2.0.2 on 2018-04-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dytp', models.ImageField(upload_to='pic/%Y/%m/%d', verbose_name='电影图片')),
                ('dybt', models.CharField(max_length=10, verbose_name='电影标题')),
                ('dydz', models.CharField(max_length=200, verbose_name='电影地址')),
            ],
        ),
        migrations.CreateModel(
            name='DyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=10, verbose_name='类别名称')),
            ],
        ),
        migrations.AddField(
            model_name='dy',
            name='dyclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyy.DyClass', verbose_name='电影类别'),
        ),
    ]
