# Generated by Django 2.0.2 on 2018-04-27 15:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dyy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wzbt', models.CharField(max_length=20, verbose_name='文章标题')),
                ('wzzz', models.CharField(max_length=10, verbose_name='文章类别')),
                ('wznr', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='WzLb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbmc', models.CharField(max_length=10, verbose_name='文章类别')),
            ],
        ),
    ]
