# Generated by Django 2.0.2 on 2018-04-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyy', '0002_wz_wzlb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WzLb',
        ),
        migrations.RemoveField(
            model_name='wz',
            name='wzzz',
        ),
    ]
